development: &non_production_settings
  site_url: http://localhost:3000
  site_name: Seed
  site_description: a Common Sense CMS from The Media Collective
  admin_email: example@gmail.com
  errors_email: example@gmail.com
  
test:
  <<: *non_production_settings
  
production:
  site_url: http://www.example.com
  site_name: Seed
  site_description: a Common Sense CMS from The Media Collective
  admin_email: example@gmail.com
  errors_email: example@gmail.com