development: &non_production_settings
  
  # General Settins
  site_url: http://localhost:3000
  site_name: Seed
  site_description: a Common Sense CMS from The Media Collective
  admin_email: example@gmail.com
  
  # Akismet api key for comment spam protection
  # http://akismet.com/
  akismet_key: abc123
  
  # Layout Settings
  enable_secondary_menu: false
  primary_menu_orientation: vertical
  secondary_menu_orientation: vertical
  
test:
  <<: *non_production_settings
  
production:
  site_url: http://www.example.com
  site_name: Seed
  site_description: a Common Sense CMS from The Media Collective
  admin_email: example@gmail.com
  
  # Akismet api key for comment spam protection
  # http://akismet.com/
  akismet_key: abc123
  
  # Layout Settings
  enable_secondary_menu: false
  primary_menu_orientation: vertical
  secondary_menu_orientation: vertical